"""Ansible playbook generation and provisioning from machine manifest."""

from __future__ import annotations

import json
import logging
import os
import socket
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

PLAYBOOK_HEADER = """# Auto-generated by AntBot — regenerated from manifest.json
# Machine: {hostname}
# Generated: {generated}
#
# Usage: ansible-playbook playbook.yml [--tags brew,vscode,...]
# Requires: NAS mounted at backup_root BEFORE running this playbook.
---
- name: Provision {hostname}
  hosts: localhost
  connection: local
  become: false

  vars:
    machine_dir: "{machine_dir}"

  tasks:
"""


def generate_playbook(manifest_json: str, backup_root: str) -> str:
    """Generate an Ansible playbook from a machine manifest JSON string."""
    m = json.loads(manifest_json)
    hostname = m.get("hostname", socket.gethostname().lower())
    machine_dir = os.path.join(backup_root, "Machines", hostname)
    generated = m.get("generated", "unknown")

    lines = [PLAYBOOK_HEADER.format(
        hostname=hostname, generated=generated, machine_dir=machine_dir,
    )]

    # Homebrew formulae
    formulae = m.get("homebrew", {}).get("formulae", [])
    if formulae:
        lines.append(_task("Install Homebrew formulae", "brew", [
            f"    community.general.homebrew:",
            f"      name: \"{{{{ item }}}}\"",
            f"      state: present",
            f"    loop:",
        ] + [f"      - {f}" for f in formulae]))

    # Homebrew casks
    casks = m.get("homebrew", {}).get("casks", [])
    if casks:
        lines.append(_task("Install Homebrew casks", "brew", [
            f"    community.general.homebrew_cask:",
            f"      name: \"{{{{ item }}}}\"",
            f"      state: present",
            f"    loop:",
        ] + [f"      - {c}" for c in casks]))

    # Shell configs (dotfiles)
    lines.append(_task("Restore dotfiles", "dotfiles", [
        f"    copy:",
        f"      src: \"{{{{ machine_dir }}}}/dotfiles/{{{{ item }}}}\"",
        f"      dest: \"{{{{ ansible_env.HOME }}}}/{{{{ item }}}}\"",
        f"      mode: '0644'",
        f"    loop:",
        f"      - .zshrc",
        f"      - .zprofile",
        f"      - .gitconfig",
        f"    ignore_errors: true",
    ]))

    # SSH config + public keys
    lines.append(_task("Restore SSH config", "ssh", [
        f"    copy:",
        f"      src: \"{{{{ machine_dir }}}}/ssh/{{{{ item }}}}\"",
        f"      dest: \"{{{{ ansible_env.HOME }}}}/.ssh/{{{{ item }}}}\"",
        f"      mode: '0644'",
        f"    loop:",
        f"      - config",
        f"      - known_hosts",
        f"    ignore_errors: true",
    ]))

    ssh_keys = m.get("ssh", {}).get("keys", [])
    if ssh_keys:
        lines.append(_task("Restore SSH public keys", "ssh", [
            f"    copy:",
            f"      src: \"{{{{ machine_dir }}}}/ssh/{{{{ item }}}}.pub\"",
            f"      dest: \"{{{{ ansible_env.HOME }}}}/.ssh/{{{{ item }}}}.pub\"",
            f"      mode: '0644'",
            f"    loop:",
        ] + [f"      - {k}" for k in ssh_keys]))

    # NOTE about private keys
    lines.append("    # Private SSH keys are NOT restored by this playbook.")
    lines.append("    # Run `antbot restore-keys` separately.\n")

    # Python packages
    py_pkgs = m.get("python", {}).get("packages", [])
    if py_pkgs:
        lines.append(_task("Install Python global packages", "python", [
            f"    pip:",
            f"      name: \"{{{{ item }}}}\"",
            f"      state: present",
            f"      executable: pip3",
            f"    loop:",
        ] + [f"      - {p}" for p in py_pkgs[:20]]))  # cap at 20

    # Node packages
    node_pkgs = m.get("node", {}).get("packages", [])
    if node_pkgs:
        lines.append(_task("Install Node global packages", "node", [
            f"    npm:",
            f"      name: \"{{{{ item }}}}\"",
            f"      global: true",
            f"      state: present",
            f"    loop:",
        ] + [f"      - {p}" for p in node_pkgs[:20]]))

    # VS Code settings
    lines.append(_task("Restore VS Code settings", "vscode", [
        f"    copy:",
        f"      src: \"{{{{ machine_dir }}}}/vscode/{{{{ item }}}}\"",
        f"      dest: \"{{{{ ansible_env.HOME }}}}/Library/Application Support/Code/User/{{{{ item }}}}\"",
        f"      mode: '0644'",
        f"    loop:",
        f"      - settings.json",
        f"      - keybindings.json",
        f"    ignore_errors: true",
    ]))

    # VS Code extensions
    vs_exts = m.get("vscode", {}).get("extensions", [])
    if vs_exts:
        lines.append(_task("Install VS Code extensions", "vscode", [
            f"    shell: \"code --install-extension {{{{ item }}}}\"",
            f"    loop:",
        ] + [f"      - {e}" for e in vs_exts[:30]] + [
            f"    ignore_errors: true",
        ]))

    # Docker images
    images = m.get("docker", {}).get("images", [])
    if images:
        # Filter out <none> and dangling
        images = [i for i in images if "<none>" not in i]
        if images:
            lines.append(_task("Pull Docker images", "docker", [
                f"    community.docker.docker_image:",
                f"      name: \"{{{{ item }}}}\"",
                f"      source: pull",
                f"    loop:",
            ] + [f"      - {i}" for i in images[:20]] + [
                f"    ignore_errors: true",
            ]))

    # Clone projects (from manifest project list if available)
    projects = m.get("projects", [])
    if projects:
        lines.append(_task("Create project directories", "projects", [
            f"    file:",
            f"      path: \"{{{{ ansible_env.HOME }}}}/DevHub_stark/factory\"",
            f"      state: directory",
            f"      mode: '0755'",
        ]))
        for proj in projects:
            remote = proj.get("remote", "")
            proj_path = proj.get("path", "").replace("~", "{{ ansible_env.HOME }}")
            branch = proj.get("branch", "main")
            if remote:
                lines.append(_task(f"Clone {proj.get('name', 'project')}", "projects", [
                    f"    git:",
                    f"      repo: \"{remote}\"",
                    f"      dest: \"{proj_path}\"",
                    f"      version: \"{branch}\"",
                    f"      accept_hostkey: true",
                    f"    ignore_errors: true",
                ]))

    # Verification
    lines.append(_task("Run verification manifest", "verify", [
        f"    shell: antbot backup --manifest --dry-run",
        f"    register: verify_result",
        f"    ignore_errors: true",
    ]))

    return "\n".join(lines)


def _task(name: str, tag: str, body_lines: list[str]) -> str:
    """Format an Ansible task."""
    lines = [f"    - name: {name}"]
    lines.extend(body_lines)
    lines.append(f"      tags: [{tag}]")
    lines.append("")
    return "\n".join(lines)


def save_playbook(manifest_json: str, backup_root: str, dry_run: bool = True) -> dict:
    """Generate and save playbook to NAS."""
    hostname = json.loads(manifest_json).get("hostname", socket.gethostname().lower())
    playbook_path = os.path.join(backup_root, "Machines", hostname, "playbook.yml")

    content = generate_playbook(manifest_json, backup_root)

    if not dry_run:
        os.makedirs(os.path.dirname(playbook_path), exist_ok=True)
        with open(playbook_path, "w") as f:
            f.write(content)

    return {"ok": True, "path": playbook_path, "dry_run": dry_run, "lines": content.count("\n")}


def run_playbook(playbook_path: str, tags: list[str] | None = None, dry_run: bool = False) -> dict:
    """Run an Ansible playbook."""
    cmd = ["ansible-playbook", playbook_path]
    if tags:
        cmd.extend(["--tags", ",".join(tags)])
    if dry_run:
        cmd.append("--check")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        return {
            "ok": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
        }
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "playbook timed out after 600s"}
    except FileNotFoundError:
        return {"ok": False, "error": "ansible-playbook not found — install with: brew install ansible"}
